server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://119.29.130.179:3306/liu_it?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root99
    driver-class-name: com.mysql.cj.jdbc.Driver
  # HTTP ENCODING
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:com.dkm.demo.dao.mapper/*.xml
  #配置别名
  type-aliases-package: com.dkm.demo.entity
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true

app:
  workerId: 1
  dataCenterId: 2
